"use client";
import { useEffect, useState } from "react";
import { createClient, type User } from "@supabase/supabase-js";
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!, { auth: { flowType: "implicit" } });
type Work = { id: string; word: string; project: string; status: string; submitted_at: string; display_image_path: string; raw_file_path: string };
export default function Workspace() {
  const [user, setUser] = useState<User | null>(null), [email, setEmail] = useState(""), [notice, setNotice] = useState(""), [works, setWorks] = useState<Work[]>([]), [project, setProject] = useState(""), [word, setWord] = useState(""), [story, setStory] = useState(""), [image, setImage] = useState<File | null>(null), [raw, setRaw] = useState<File | null>(null), [busy, setBusy] = useState(false);
  const load = async () => { const { data } = await supabase.from("submissions").select("id, word, project, status, submitted_at, display_image_path, raw_file_path").order("submitted_at", { ascending: false }); setWorks(data ?? []); };
  useEffect(() => { supabase.auth.getUser().then(async ({ data }) => { setUser(data.user); if (data.user) await load(); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => { setUser(session?.user ?? null); if (session?.user) void load(); }); return () => listener.subscription.unsubscribe(); }, []);
  async function signIn(event: React.FormEvent) { event.preventDefault(); setNotice("Sending your private sign-in link..."); const { error } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: `${window.location.origin}/account` } }); setNotice(error ? "The link could not be sent. Check your email service settings and try again." : "Check your email for your private sign-in link."); }
  async function publish(event: React.FormEvent) { event.preventDefault(); if (!user || !image || !raw) return setNotice("Add the final image and its source file."); setBusy(true); const folder = `${user.id}/${crypto.randomUUID()}`, display = `${folder}/final-${image.name}`, source = `${folder}/source-${raw.name}`; const a = await supabase.storage.from("submissions").upload(display, image), b = a.error ? { error: a.error } : await supabase.storage.from("submissions").upload(source, raw); if (a.error || b.error) { setBusy(false); return setNotice("The files could not be uploaded."); } const { error } = await supabase.from("submissions").insert({ user_id: user.id, project: project.trim().toUpperCase(), word: word.trim().toUpperCase(), story: story.trim(), display_image_path: display, raw_file_path: source, status: "approved" }); if (error) { await supabase.storage.from("submissions").remove([display, source]); setNotice(error.message); } else { setProject(""); setWord(""); setStory(""); setImage(null); setRaw(null); setNotice("Published to the current rotation."); await load(); } setBusy(false); }
  async function archive(item: Work) { const { error } = await supabase.from("submissions").update({ status: item.status === "archived" ? "approved" : "archived" }).eq("id", item.id); if (error) return setNotice("That change could not be saved."); await load(); }
  if (!user) return <main className="account-page"><header className="account-header"><a href="/">← INSIGHTFOOLISH</a><span>PRIVATE WORKSPACE</span></header><section className="account-intro"><p>OWNER ACCESS</p><h1>PUBLISH<br />WORK.</h1><form onSubmit={signIn}><label>YOUR EMAIL</label><div><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /><button>EMAIL ME A LINK →</button></div></form><small>{notice}</small></section></main>;
  return <main className="account-page"><header className="account-header"><a href="/">← INSIGHTFOOLISH</a><span>PRIVATE WORKSPACE</span></header><section className="account-intro"><p>IMAGE PUBLISHER</p><h1>YOUR<br />WORK.</h1><div className="account-email">{user.email}</div><form className="submission-form" onSubmit={publish}><span>ADD TO PORTFOLIO</span><label>PROJECT<input value={project} onChange={(e) => setProject(e.target.value)} required placeholder="e.g. STREET STUDIES" /></label><label>IMAGE TITLE<input value={word} onChange={(e) => setWord(e.target.value)} required placeholder="One word" /></label><label>NOTES<textarea value={story} onChange={(e) => setStory(e.target.value)} required /></label><label>FINAL IMAGE<input type="file" accept="image/*" onChange={(e) => setImage(e.target.files?.[0] ?? null)} required /></label><label>SOURCE FILE<input type="file" onChange={(e) => setRaw(e.target.files?.[0] ?? null)} required /></label><button disabled={busy}>{busy ? "UPLOADING..." : "PUBLISH TO CURRENT PROJECT →"}</button></form><small className="account-notice">{notice}</small><div className="my-work"><span>PROJECT ARCHIVE</span>{works.map((item) => <article key={item.id}><div><strong>{item.word}</strong><small>{item.project} / {item.status.toUpperCase()}</small></div><button onClick={() => void archive(item)}>{item.status === "archived" ? "RESTORE" : "ARCHIVE"}</button></article>)}</div><button className="signout" onClick={() => void supabase.auth.signOut()}>SIGN OUT</button></section></main>;
}
